insert into user values(101, sysdate(), 'some')
insert into user values(102, sysdate(), 'some1')
insert into user values(103, sysdate(), 'some2')
insert into post values(1101, 'My First Post', 101)
insert into post values(1102, 'My Second Post', 101)